config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    collection do
      post :confirm
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :content, presence: true
    validates :content,    length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def new
    if params[:back]
      @contact = Contact.new(blog_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: "編集しました！"
    else
      render 'new'
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path, notice:"削除しました！"
  end

  def confirm
    @contact = Contact.new(contact_params)
    render :new if @contact.invalid?
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_contacts_path
            elsif action_name == 'edit'
            contact_path
        end
    end
end

app/views/contacts/_form.html.erb
<%= form_with(model: @contact, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= notice %></p>
  
  <div class="contact_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="contact_email">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="contact_content">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit "create"%>
<% end %>

<%= link_to 'ブログ一覧画面にもどる', contacts_path %>

app/views/contacts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @contact, url: contacts_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :content %>

  <p>名前:<%= @contact.name %></p>
  <p>メール:<%= @contact.email %></p>
  <p>本文:<%= @contact.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @contzct, url: new_contact_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/contacts/edit.html.erb
<%= form_with(model: @contact, local: true) do |form| %>
    <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= notice %></p>
  
  <div class="contact_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="contact_email">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="contact_content">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit "update"%>
<% end %>

app/views/contacts/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>名前</th>
    <th>email</th>
    <th>内容</th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.content %></td>
    
    <td><%= link_to '詳細を確認する', contact_path(contact.id) %></td>
    <td><%= link_to "ブログを編集する", edit_contact_path(contact.id), data: { confirm: '本当に編集していいですか？' }%></td>
    <td><%= link_to 'ブログを削除する', contact_path(contact.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }%></td>
  </tr>
<% end %>
</table>

<%= link_to 'ブログ一覧画面にもどる', contacts_path %>
<%= link_to '新しくブログを投稿する', new_contact_path %>

app/views/contacts/new.html.erb
  <h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/contacts/show.html.erb
<h1>ブログ詳細画面</h1>
<p>名前: <%= @contact.name %></p>
<p>メール: <%= @contact.email %></p>
<p>内容: <%= @contact.content %></p>

<%= link_to 'ブログ一覧画面にもどる', contacts_path %>
<%= link_to '新しくブログを投稿する', new_contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>